# Distributed under the terms of the GNU General Public License v2

EAPI=7

inherit cargo

DESCRIPTION=""
HOMEPAGE="https://github.com/lu-zero/cargo-c"
SRC_URI="https://api.github.com/repos/lu-zero/cargo-c/tarball/v0.10.24 -> cargo-c-aarch64-linux-android.tar.gz-0.10.24.tar.gz
https://crates.io/api/v1/crates/adler2/2.0.1/download -> adler2-2.0.1.crate
https://crates.io/api/v1/crates/aho-corasick/1.1.4/download -> aho-corasick-1.1.4.crate
https://crates.io/api/v1/crates/allocator-api2/0.2.21/download -> allocator-api2-0.2.21.crate
https://crates.io/api/v1/crates/android_system_properties/0.1.5/download -> android_system_properties-0.1.5.crate
https://crates.io/api/v1/crates/annotate-snippets/0.12.16/download -> annotate-snippets-0.12.16.crate
https://crates.io/api/v1/crates/anstream/1.0.0/download -> anstream-1.0.0.crate
https://crates.io/api/v1/crates/anstyle/1.0.14/download -> anstyle-1.0.14.crate
https://crates.io/api/v1/crates/anstyle-hyperlink/1.0.2/download -> anstyle-hyperlink-1.0.2.crate
https://crates.io/api/v1/crates/anstyle-parse/1.0.0/download -> anstyle-parse-1.0.0.crate
https://crates.io/api/v1/crates/anstyle-progress/0.1.3/download -> anstyle-progress-0.1.3.crate
https://crates.io/api/v1/crates/anstyle-query/1.1.5/download -> anstyle-query-1.1.5.crate
https://crates.io/api/v1/crates/anstyle-wincon/3.0.11/download -> anstyle-wincon-3.0.11.crate
https://crates.io/api/v1/crates/anyhow/1.0.104/download -> anyhow-1.0.104.crate
https://crates.io/api/v1/crates/ar_archive_writer/0.5.2/download -> ar_archive_writer-0.5.2.crate
https://crates.io/api/v1/crates/arc-swap/1.9.2/download -> arc-swap-1.9.2.crate
https://crates.io/api/v1/crates/arrayref/0.3.9/download -> arrayref-0.3.9.crate
https://crates.io/api/v1/crates/arrayvec/0.7.8/download -> arrayvec-0.7.8.crate
https://crates.io/api/v1/crates/async-trait/0.1.91/download -> async-trait-0.1.91.crate
https://crates.io/api/v1/crates/autocfg/1.5.1/download -> autocfg-1.5.1.crate
https://crates.io/api/v1/crates/base16ct/0.2.0/download -> base16ct-0.2.0.crate
https://crates.io/api/v1/crates/base64/0.22.1/download -> base64-0.22.1.crate
https://crates.io/api/v1/crates/base64ct/1.8.3/download -> base64ct-1.8.3.crate
https://crates.io/api/v1/crates/bitflags/1.3.2/download -> bitflags-1.3.2.crate
https://crates.io/api/v1/crates/bitflags/2.13.1/download -> bitflags-2.13.1.crate
https://crates.io/api/v1/crates/bitmaps/2.1.0/download -> bitmaps-2.1.0.crate
https://crates.io/api/v1/crates/blake3/1.8.5/download -> blake3-1.8.5.crate
https://crates.io/api/v1/crates/block-buffer/0.10.4/download -> block-buffer-0.10.4.crate
https://crates.io/api/v1/crates/block-buffer/0.12.1/download -> block-buffer-0.12.1.crate
https://crates.io/api/v1/crates/block2/0.6.2/download -> block2-0.6.2.crate
https://crates.io/api/v1/crates/bstr/1.13.0/download -> bstr-1.13.0.crate
https://crates.io/api/v1/crates/bumpalo/3.20.3/download -> bumpalo-3.20.3.crate
https://crates.io/api/v1/crates/byteorder/1.5.0/download -> byteorder-1.5.0.crate
https://crates.io/api/v1/crates/bytes/1.12.1/download -> bytes-1.12.1.crate
https://crates.io/api/v1/crates/camino/1.2.4/download -> camino-1.2.4.crate
https://crates.io/api/v1/crates/cargo/0.98.0/download -> cargo-0.98.0.crate
https://crates.io/api/v1/crates/cargo-credential/0.4.10/download -> cargo-credential-0.4.10.crate
https://crates.io/api/v1/crates/cargo-credential-libsecret/0.5.8/download -> cargo-credential-libsecret-0.5.8.crate
https://crates.io/api/v1/crates/cargo-credential-macos-keychain/0.4.23/download -> cargo-credential-macos-keychain-0.4.23.crate
https://crates.io/api/v1/crates/cargo-credential-wincred/0.4.23/download -> cargo-credential-wincred-0.4.23.crate
https://crates.io/api/v1/crates/cargo-platform/0.3.3/download -> cargo-platform-0.3.3.crate
https://crates.io/api/v1/crates/cargo-util/0.2.30/download -> cargo-util-0.2.30.crate
https://crates.io/api/v1/crates/cargo-util-schemas/0.14.1/download -> cargo-util-schemas-0.14.1.crate
https://crates.io/api/v1/crates/cargo-util-terminal/0.1.0/download -> cargo-util-terminal-0.1.0.crate
https://crates.io/api/v1/crates/cbindgen/0.29.4/download -> cbindgen-0.29.4.crate
https://crates.io/api/v1/crates/cc/1.3.0/download -> cc-1.3.0.crate
https://crates.io/api/v1/crates/cfg-if/1.0.4/download -> cfg-if-1.0.4.crate
https://crates.io/api/v1/crates/cfg_aliases/0.2.2/download -> cfg_aliases-0.2.2.crate
https://crates.io/api/v1/crates/chacha20/0.10.1/download -> chacha20-0.10.1.crate
https://crates.io/api/v1/crates/clap/4.6.2/download -> clap-4.6.2.crate
https://crates.io/api/v1/crates/clap_builder/4.6.2/download -> clap_builder-4.6.2.crate
https://crates.io/api/v1/crates/clap_complete/4.6.7/download -> clap_complete-4.6.7.crate
https://crates.io/api/v1/crates/clap_derive/4.6.1/download -> clap_derive-4.6.1.crate
https://crates.io/api/v1/crates/clap_lex/1.1.0/download -> clap_lex-1.1.0.crate
https://crates.io/api/v1/crates/clru/0.6.3/download -> clru-0.6.3.crate
https://crates.io/api/v1/crates/cmov/0.5.4/download -> cmov-0.5.4.crate
https://crates.io/api/v1/crates/color-print/0.3.7/download -> color-print-0.3.7.crate
https://crates.io/api/v1/crates/color-print-proc-macro/0.3.7/download -> color-print-proc-macro-0.3.7.crate
https://crates.io/api/v1/crates/colorchoice/1.0.5/download -> colorchoice-1.0.5.crate
https://crates.io/api/v1/crates/const-oid/0.9.6/download -> const-oid-0.9.6.crate
https://crates.io/api/v1/crates/const-oid/0.10.2/download -> const-oid-0.10.2.crate
https://crates.io/api/v1/crates/constant_time_eq/0.4.2/download -> constant_time_eq-0.4.2.crate
https://crates.io/api/v1/crates/core-foundation/0.10.1/download -> core-foundation-0.10.1.crate
https://crates.io/api/v1/crates/core-foundation-sys/0.8.7/download -> core-foundation-sys-0.8.7.crate
https://crates.io/api/v1/crates/cpufeatures/0.2.17/download -> cpufeatures-0.2.17.crate
https://crates.io/api/v1/crates/cpufeatures/0.3.0/download -> cpufeatures-0.3.0.crate
https://crates.io/api/v1/crates/crates-io/0.41.0/download -> crates-io-0.41.0.crate
https://crates.io/api/v1/crates/crc32fast/1.5.0/download -> crc32fast-1.5.0.crate
https://crates.io/api/v1/crates/crossbeam-channel/0.5.16/download -> crossbeam-channel-0.5.16.crate
https://crates.io/api/v1/crates/crossbeam-deque/0.8.7/download -> crossbeam-deque-0.8.7.crate
https://crates.io/api/v1/crates/crossbeam-epoch/0.9.20/download -> crossbeam-epoch-0.9.20.crate
https://crates.io/api/v1/crates/crossbeam-utils/0.8.22/download -> crossbeam-utils-0.8.22.crate
https://crates.io/api/v1/crates/crypto-bigint/0.5.5/download -> crypto-bigint-0.5.5.crate
https://crates.io/api/v1/crates/crypto-common/0.1.6/download -> crypto-common-0.1.6.crate
https://crates.io/api/v1/crates/crypto-common/0.2.2/download -> crypto-common-0.2.2.crate
https://crates.io/api/v1/crates/ct-codecs/1.1.7/download -> ct-codecs-1.1.7.crate
https://crates.io/api/v1/crates/ctutils/0.4.2/download -> ctutils-0.4.2.crate
https://crates.io/api/v1/crates/curl/0.4.50/download -> curl-0.4.50.crate
https://crates.io/api/v1/crates/curl-sys/0.4.90+curl-8.21.0/download -> curl-sys-0.4.90+curl-8.21.0.crate
https://crates.io/api/v1/crates/dashmap/6.2.1/download -> dashmap-6.2.1.crate
https://crates.io/api/v1/crates/defmt/1.1.1/download -> defmt-1.1.1.crate
https://crates.io/api/v1/crates/defmt-macros/1.1.1/download -> defmt-macros-1.1.1.crate
https://crates.io/api/v1/crates/defmt-parser/1.0.0/download -> defmt-parser-1.0.0.crate
https://crates.io/api/v1/crates/der/0.7.10/download -> der-0.7.10.crate
https://crates.io/api/v1/crates/deranged/0.5.8/download -> deranged-0.5.8.crate
https://crates.io/api/v1/crates/digest/0.10.7/download -> digest-0.10.7.crate
https://crates.io/api/v1/crates/digest/0.11.3/download -> digest-0.11.3.crate
https://crates.io/api/v1/crates/dispatch2/0.3.1/download -> dispatch2-0.3.1.crate
https://crates.io/api/v1/crates/displaydoc/0.2.6/download -> displaydoc-0.2.6.crate
https://crates.io/api/v1/crates/dunce/1.0.5/download -> dunce-1.0.5.crate
https://crates.io/api/v1/crates/ecdsa/0.16.9/download -> ecdsa-0.16.9.crate
https://crates.io/api/v1/crates/ed25519-compact/2.3.1/download -> ed25519-compact-2.3.1.crate
https://crates.io/api/v1/crates/either/1.16.0/download -> either-1.16.0.crate
https://crates.io/api/v1/crates/elliptic-curve/0.13.8/download -> elliptic-curve-0.13.8.crate
https://crates.io/api/v1/crates/encoding_rs/0.8.35/download -> encoding_rs-0.8.35.crate
https://crates.io/api/v1/crates/equivalent/1.0.2/download -> equivalent-1.0.2.crate
https://crates.io/api/v1/crates/erased-serde/0.4.10/download -> erased-serde-0.4.10.crate
https://crates.io/api/v1/crates/errno/0.3.14/download -> errno-0.3.14.crate
https://crates.io/api/v1/crates/fallible-iterator/0.3.0/download -> fallible-iterator-0.3.0.crate
https://crates.io/api/v1/crates/fallible-streaming-iterator/0.1.9/download -> fallible-streaming-iterator-0.1.9.crate
https://crates.io/api/v1/crates/faster-hex/0.10.0/download -> faster-hex-0.10.0.crate
https://crates.io/api/v1/crates/fastrand/2.4.1/download -> fastrand-2.4.1.crate
https://crates.io/api/v1/crates/ff/0.13.1/download -> ff-0.13.1.crate
https://crates.io/api/v1/crates/fiat-crypto/0.3.0/download -> fiat-crypto-0.3.0.crate
https://crates.io/api/v1/crates/filetime/0.2.29/download -> filetime-0.2.29.crate
https://crates.io/api/v1/crates/find-msvc-tools/0.1.9/download -> find-msvc-tools-0.1.9.crate
https://crates.io/api/v1/crates/flate2/1.1.9/download -> flate2-1.1.9.crate
https://crates.io/api/v1/crates/fnv/1.0.7/download -> fnv-1.0.7.crate
https://crates.io/api/v1/crates/foldhash/0.2.0/download -> foldhash-0.2.0.crate
https://crates.io/api/v1/crates/foreign-types/0.3.2/download -> foreign-types-0.3.2.crate
https://crates.io/api/v1/crates/foreign-types-shared/0.1.1/download -> foreign-types-shared-0.1.1.crate
https://crates.io/api/v1/crates/form_urlencoded/1.2.2/download -> form_urlencoded-1.2.2.crate
https://crates.io/api/v1/crates/futures/0.3.33/download -> futures-0.3.33.crate
https://crates.io/api/v1/crates/futures-channel/0.3.33/download -> futures-channel-0.3.33.crate
https://crates.io/api/v1/crates/futures-core/0.3.33/download -> futures-core-0.3.33.crate
https://crates.io/api/v1/crates/futures-executor/0.3.33/download -> futures-executor-0.3.33.crate
https://crates.io/api/v1/crates/futures-io/0.3.33/download -> futures-io-0.3.33.crate
https://crates.io/api/v1/crates/futures-macro/0.3.33/download -> futures-macro-0.3.33.crate
https://crates.io/api/v1/crates/futures-sink/0.3.33/download -> futures-sink-0.3.33.crate
https://crates.io/api/v1/crates/futures-task/0.3.33/download -> futures-task-0.3.33.crate
https://crates.io/api/v1/crates/futures-timer/3.0.4/download -> futures-timer-3.0.4.crate
https://crates.io/api/v1/crates/futures-util/0.3.33/download -> futures-util-0.3.33.crate
https://crates.io/api/v1/crates/generic-array/0.14.9/download -> generic-array-0.14.9.crate
https://crates.io/api/v1/crates/getrandom/0.2.17/download -> getrandom-0.2.17.crate
https://crates.io/api/v1/crates/getrandom/0.4.3/download -> getrandom-0.4.3.crate
https://crates.io/api/v1/crates/git2/0.20.4/download -> git2-0.20.4.crate
https://crates.io/api/v1/crates/git2-curl/0.21.0/download -> git2-curl-0.21.0.crate
https://crates.io/api/v1/crates/gix/0.83.0/download -> gix-0.83.0.crate
https://crates.io/api/v1/crates/gix-actor/0.41.1/download -> gix-actor-0.41.1.crate
https://crates.io/api/v1/crates/gix-archive/0.32.0/download -> gix-archive-0.32.0.crate
https://crates.io/api/v1/crates/gix-attributes/0.33.2/download -> gix-attributes-0.33.2.crate
https://crates.io/api/v1/crates/gix-bitmap/0.3.2/download -> gix-bitmap-0.3.2.crate
https://crates.io/api/v1/crates/gix-blame/0.13.0/download -> gix-blame-0.13.0.crate
https://crates.io/api/v1/crates/gix-chunk/0.7.2/download -> gix-chunk-0.7.2.crate
https://crates.io/api/v1/crates/gix-command/0.9.1/download -> gix-command-0.9.1.crate
https://crates.io/api/v1/crates/gix-commitgraph/0.37.1/download -> gix-commitgraph-0.37.1.crate
https://crates.io/api/v1/crates/gix-config/0.56.0/download -> gix-config-0.56.0.crate
https://crates.io/api/v1/crates/gix-config-value/0.18.1/download -> gix-config-value-0.18.1.crate
https://crates.io/api/v1/crates/gix-credentials/0.38.2/download -> gix-credentials-0.38.2.crate
https://crates.io/api/v1/crates/gix-date/0.15.6/download -> gix-date-0.15.6.crate
https://crates.io/api/v1/crates/gix-diff/0.63.0/download -> gix-diff-0.63.0.crate
https://crates.io/api/v1/crates/gix-dir/0.25.0/download -> gix-dir-0.25.0.crate
https://crates.io/api/v1/crates/gix-discover/0.51.0/download -> gix-discover-0.51.0.crate
https://crates.io/api/v1/crates/gix-error/0.2.5/download -> gix-error-0.2.5.crate
https://crates.io/api/v1/crates/gix-features/0.48.1/download -> gix-features-0.48.1.crate
https://crates.io/api/v1/crates/gix-filter/0.30.0/download -> gix-filter-0.30.0.crate
https://crates.io/api/v1/crates/gix-fs/0.21.2/download -> gix-fs-0.21.2.crate
https://crates.io/api/v1/crates/gix-glob/0.26.1/download -> gix-glob-0.26.1.crate
https://crates.io/api/v1/crates/gix-hash/0.25.1/download -> gix-hash-0.25.1.crate
https://crates.io/api/v1/crates/gix-hashtable/0.15.2/download -> gix-hashtable-0.15.2.crate
https://crates.io/api/v1/crates/gix-ignore/0.21.1/download -> gix-ignore-0.21.1.crate
https://crates.io/api/v1/crates/gix-imara-diff/0.2.3/download -> gix-imara-diff-0.2.3.crate
https://crates.io/api/v1/crates/gix-index/0.51.0/download -> gix-index-0.51.0.crate
https://crates.io/api/v1/crates/gix-lock/23.0.1/download -> gix-lock-23.0.1.crate
https://crates.io/api/v1/crates/gix-merge/0.16.0/download -> gix-merge-0.16.0.crate
https://crates.io/api/v1/crates/gix-negotiate/0.31.0/download -> gix-negotiate-0.31.0.crate
https://crates.io/api/v1/crates/gix-object/0.60.0/download -> gix-object-0.60.0.crate
https://crates.io/api/v1/crates/gix-odb/0.80.0/download -> gix-odb-0.80.0.crate
https://crates.io/api/v1/crates/gix-pack/0.70.0/download -> gix-pack-0.70.0.crate
https://crates.io/api/v1/crates/gix-packetline/0.21.5/download -> gix-packetline-0.21.5.crate
https://crates.io/api/v1/crates/gix-path/0.12.2/download -> gix-path-0.12.2.crate
https://crates.io/api/v1/crates/gix-pathspec/0.18.1/download -> gix-pathspec-0.18.1.crate
https://crates.io/api/v1/crates/gix-prompt/0.15.1/download -> gix-prompt-0.15.1.crate
https://crates.io/api/v1/crates/gix-protocol/0.61.0/download -> gix-protocol-0.61.0.crate
https://crates.io/api/v1/crates/gix-quote/0.7.2/download -> gix-quote-0.7.2.crate
https://crates.io/api/v1/crates/gix-ref/0.63.0/download -> gix-ref-0.63.0.crate
https://crates.io/api/v1/crates/gix-refspec/0.41.0/download -> gix-refspec-0.41.0.crate
https://crates.io/api/v1/crates/gix-revision/0.45.0/download -> gix-revision-0.45.0.crate
https://crates.io/api/v1/crates/gix-revwalk/0.31.0/download -> gix-revwalk-0.31.0.crate
https://crates.io/api/v1/crates/gix-sec/0.14.1/download -> gix-sec-0.14.1.crate
https://crates.io/api/v1/crates/gix-shallow/0.12.1/download -> gix-shallow-0.12.1.crate
https://crates.io/api/v1/crates/gix-status/0.30.0/download -> gix-status-0.30.0.crate
https://crates.io/api/v1/crates/gix-submodule/0.30.0/download -> gix-submodule-0.30.0.crate
https://crates.io/api/v1/crates/gix-tempfile/23.0.2/download -> gix-tempfile-23.0.2.crate
https://crates.io/api/v1/crates/gix-trace/0.1.20/download -> gix-trace-0.1.20.crate
https://crates.io/api/v1/crates/gix-transport/0.57.2/download -> gix-transport-0.57.2.crate
https://crates.io/api/v1/crates/gix-traverse/0.57.0/download -> gix-traverse-0.57.0.crate
https://crates.io/api/v1/crates/gix-url/0.36.2/download -> gix-url-0.36.2.crate
https://crates.io/api/v1/crates/gix-utils/0.3.4/download -> gix-utils-0.3.4.crate
https://crates.io/api/v1/crates/gix-validate/0.11.2/download -> gix-validate-0.11.2.crate
https://crates.io/api/v1/crates/gix-worktree/0.52.0/download -> gix-worktree-0.52.0.crate
https://crates.io/api/v1/crates/gix-worktree-state/0.30.0/download -> gix-worktree-state-0.30.0.crate
https://crates.io/api/v1/crates/gix-worktree-stream/0.32.0/download -> gix-worktree-stream-0.32.0.crate
https://crates.io/api/v1/crates/glob/0.3.3/download -> glob-0.3.3.crate
https://crates.io/api/v1/crates/globset/0.4.19/download -> globset-0.4.19.crate
https://crates.io/api/v1/crates/group/0.13.0/download -> group-0.13.0.crate
https://crates.io/api/v1/crates/hash32/0.3.1/download -> hash32-0.3.1.crate
https://crates.io/api/v1/crates/hashbrown/0.14.5/download -> hashbrown-0.14.5.crate
https://crates.io/api/v1/crates/hashbrown/0.16.1/download -> hashbrown-0.16.1.crate
https://crates.io/api/v1/crates/hashbrown/0.17.1/download -> hashbrown-0.17.1.crate
https://crates.io/api/v1/crates/hashlink/0.11.1/download -> hashlink-0.11.1.crate
https://crates.io/api/v1/crates/heapless/0.8.0/download -> heapless-0.8.0.crate
https://crates.io/api/v1/crates/heck/0.5.0/download -> heck-0.5.0.crate
https://crates.io/api/v1/crates/hex/0.4.3/download -> hex-0.4.3.crate
https://crates.io/api/v1/crates/hkdf/0.12.4/download -> hkdf-0.12.4.crate
https://crates.io/api/v1/crates/hmac/0.12.1/download -> hmac-0.12.1.crate
https://crates.io/api/v1/crates/hmac/0.13.0/download -> hmac-0.13.0.crate
https://crates.io/api/v1/crates/home/0.5.12/download -> home-0.5.12.crate
https://crates.io/api/v1/crates/http/1.4.2/download -> http-1.4.2.crate
https://crates.io/api/v1/crates/http-auth/0.1.10/download -> http-auth-0.1.10.crate
https://crates.io/api/v1/crates/hybrid-array/0.4.13/download -> hybrid-array-0.4.13.crate
https://crates.io/api/v1/crates/icu_collections/2.2.0/download -> icu_collections-2.2.0.crate
https://crates.io/api/v1/crates/icu_locale_core/2.2.0/download -> icu_locale_core-2.2.0.crate
https://crates.io/api/v1/crates/icu_normalizer/2.2.0/download -> icu_normalizer-2.2.0.crate
https://crates.io/api/v1/crates/icu_normalizer_data/2.2.0/download -> icu_normalizer_data-2.2.0.crate
https://crates.io/api/v1/crates/icu_properties/2.2.0/download -> icu_properties-2.2.0.crate
https://crates.io/api/v1/crates/icu_properties_data/2.2.0/download -> icu_properties_data-2.2.0.crate
https://crates.io/api/v1/crates/icu_provider/2.2.0/download -> icu_provider-2.2.0.crate
https://crates.io/api/v1/crates/idna/1.1.0/download -> idna-1.1.0.crate
https://crates.io/api/v1/crates/idna_adapter/1.2.2/download -> idna_adapter-1.2.2.crate
https://crates.io/api/v1/crates/ignore/0.4.30/download -> ignore-0.4.30.crate
https://crates.io/api/v1/crates/im-rc/15.1.0/download -> im-rc-15.1.0.crate
https://crates.io/api/v1/crates/implib/0.6.0/download -> implib-0.6.0.crate
https://crates.io/api/v1/crates/indexmap/2.14.0/download -> indexmap-2.14.0.crate
https://crates.io/api/v1/crates/io-close/0.3.7/download -> io-close-0.3.7.crate
https://crates.io/api/v1/crates/is_executable/1.0.6/download -> is_executable-1.0.6.crate
https://crates.io/api/v1/crates/is_terminal_polyfill/1.70.2/download -> is_terminal_polyfill-1.70.2.crate
https://crates.io/api/v1/crates/itertools/0.14.0/download -> itertools-0.14.0.crate
https://crates.io/api/v1/crates/itertools/0.15.0/download -> itertools-0.15.0.crate
https://crates.io/api/v1/crates/itoa/1.0.18/download -> itoa-1.0.18.crate
https://crates.io/api/v1/crates/jiff/0.2.33/download -> jiff-0.2.33.crate
https://crates.io/api/v1/crates/jiff-core/0.1.0/download -> jiff-core-0.1.0.crate
https://crates.io/api/v1/crates/jiff-static/0.2.33/download -> jiff-static-0.2.33.crate
https://crates.io/api/v1/crates/jiff-tzdb/0.1.8/download -> jiff-tzdb-0.1.8.crate
https://crates.io/api/v1/crates/jiff-tzdb-platform/0.1.3/download -> jiff-tzdb-platform-0.1.3.crate
https://crates.io/api/v1/crates/jobserver/0.1.35/download -> jobserver-0.1.35.crate
https://crates.io/api/v1/crates/js-sys/0.3.103/download -> js-sys-0.3.103.crate
https://crates.io/api/v1/crates/kstring/2.0.4/download -> kstring-2.0.4.crate
https://crates.io/api/v1/crates/lazy_static/1.5.0/download -> lazy_static-1.5.0.crate
https://crates.io/api/v1/crates/libc/0.2.186/download -> libc-0.2.186.crate
https://crates.io/api/v1/crates/libgit2-sys/0.18.5+1.9.4/download -> libgit2-sys-0.18.5+1.9.4.crate
https://crates.io/api/v1/crates/libloading/0.9.0/download -> libloading-0.9.0.crate
https://crates.io/api/v1/crates/libnghttp2-sys/0.1.13+1.68.1/download -> libnghttp2-sys-0.1.13+1.68.1.crate
https://crates.io/api/v1/crates/libsqlite3-sys/0.37.0/download -> libsqlite3-sys-0.37.0.crate
https://crates.io/api/v1/crates/libssh2-sys/0.3.2/download -> libssh2-sys-0.3.2.crate
https://crates.io/api/v1/crates/libz-sys/1.1.29/download -> libz-sys-1.1.29.crate
https://crates.io/api/v1/crates/linux-raw-sys/0.12.1/download -> linux-raw-sys-0.12.1.crate
https://crates.io/api/v1/crates/litemap/0.8.2/download -> litemap-0.8.2.crate
https://crates.io/api/v1/crates/lock_api/0.4.14/download -> lock_api-0.4.14.crate
https://crates.io/api/v1/crates/log/0.4.33/download -> log-0.4.33.crate
https://crates.io/api/v1/crates/matchers/0.2.0/download -> matchers-0.2.0.crate
https://crates.io/api/v1/crates/maybe-async/0.2.11/download -> maybe-async-0.2.11.crate
https://crates.io/api/v1/crates/memchr/2.8.3/download -> memchr-2.8.3.crate
https://crates.io/api/v1/crates/memmap2/0.9.11/download -> memmap2-0.9.11.crate
https://crates.io/api/v1/crates/memoffset/0.9.1/download -> memoffset-0.9.1.crate
https://crates.io/api/v1/crates/minimal-lexical/0.2.1/download -> minimal-lexical-0.2.1.crate
https://crates.io/api/v1/crates/miniz_oxide/0.8.9/download -> miniz_oxide-0.8.9.crate
https://crates.io/api/v1/crates/miow/0.6.1/download -> miow-0.6.1.crate
https://crates.io/api/v1/crates/nix/0.31.3/download -> nix-0.31.3.crate
https://crates.io/api/v1/crates/nom/7.1.3/download -> nom-7.1.3.crate
https://crates.io/api/v1/crates/nonempty/0.12.0/download -> nonempty-0.12.0.crate
https://crates.io/api/v1/crates/normpath/1.5.1/download -> normpath-1.5.1.crate
https://crates.io/api/v1/crates/nu-ansi-term/0.50.3/download -> nu-ansi-term-0.50.3.crate
https://crates.io/api/v1/crates/num-conv/0.2.2/download -> num-conv-0.2.2.crate
https://crates.io/api/v1/crates/num-traits/0.2.19/download -> num-traits-0.2.19.crate
https://crates.io/api/v1/crates/objc2/0.6.4/download -> objc2-0.6.4.crate
https://crates.io/api/v1/crates/objc2-cloud-kit/0.3.2/download -> objc2-cloud-kit-0.3.2.crate
https://crates.io/api/v1/crates/objc2-core-data/0.3.2/download -> objc2-core-data-0.3.2.crate
https://crates.io/api/v1/crates/objc2-core-foundation/0.3.2/download -> objc2-core-foundation-0.3.2.crate
https://crates.io/api/v1/crates/objc2-core-graphics/0.3.2/download -> objc2-core-graphics-0.3.2.crate
https://crates.io/api/v1/crates/objc2-core-image/0.3.2/download -> objc2-core-image-0.3.2.crate
https://crates.io/api/v1/crates/objc2-core-location/0.3.2/download -> objc2-core-location-0.3.2.crate
https://crates.io/api/v1/crates/objc2-core-text/0.3.2/download -> objc2-core-text-0.3.2.crate
https://crates.io/api/v1/crates/objc2-encode/4.1.0/download -> objc2-encode-4.1.0.crate
https://crates.io/api/v1/crates/objc2-foundation/0.3.2/download -> objc2-foundation-0.3.2.crate
https://crates.io/api/v1/crates/objc2-io-surface/0.3.2/download -> objc2-io-surface-0.3.2.crate
https://crates.io/api/v1/crates/objc2-quartz-core/0.3.2/download -> objc2-quartz-core-0.3.2.crate
https://crates.io/api/v1/crates/objc2-ui-kit/0.3.2/download -> objc2-ui-kit-0.3.2.crate
https://crates.io/api/v1/crates/objc2-user-notifications/0.3.2/download -> objc2-user-notifications-0.3.2.crate
https://crates.io/api/v1/crates/object/0.37.3/download -> object-0.37.3.crate
https://crates.io/api/v1/crates/object/0.39.1/download -> object-0.39.1.crate
https://crates.io/api/v1/crates/once_cell/1.21.4/download -> once_cell-1.21.4.crate
https://crates.io/api/v1/crates/once_cell_polyfill/1.70.2/download -> once_cell_polyfill-1.70.2.crate
https://crates.io/api/v1/crates/opener/0.8.5/download -> opener-0.8.5.crate
https://crates.io/api/v1/crates/openssl/0.10.81/download -> openssl-0.10.81.crate
https://crates.io/api/v1/crates/openssl-macros/0.1.1/download -> openssl-macros-0.1.1.crate
https://crates.io/api/v1/crates/openssl-probe/0.1.6/download -> openssl-probe-0.1.6.crate
https://crates.io/api/v1/crates/openssl-src/300.6.1+3.6.3/download -> openssl-src-300.6.1+3.6.3.crate
https://crates.io/api/v1/crates/openssl-sys/0.9.117/download -> openssl-sys-0.9.117.crate
https://crates.io/api/v1/crates/ordered-float/2.10.1/download -> ordered-float-2.10.1.crate
https://crates.io/api/v1/crates/orion/0.17.15/download -> orion-0.17.15.crate
https://crates.io/api/v1/crates/os_info/3.15.0/download -> os_info-3.15.0.crate
https://crates.io/api/v1/crates/p384/0.13.1/download -> p384-0.13.1.crate
https://crates.io/api/v1/crates/parking_lot/0.12.5/download -> parking_lot-0.12.5.crate
https://crates.io/api/v1/crates/parking_lot_core/0.9.12/download -> parking_lot_core-0.9.12.crate
https://crates.io/api/v1/crates/pasetors/0.7.8/download -> pasetors-0.7.8.crate
https://crates.io/api/v1/crates/pathdiff/0.2.3/download -> pathdiff-0.2.3.crate
https://crates.io/api/v1/crates/pem-rfc7468/0.7.0/download -> pem-rfc7468-0.7.0.crate
https://crates.io/api/v1/crates/percent-encoding/2.3.2/download -> percent-encoding-2.3.2.crate
https://crates.io/api/v1/crates/pin-project-lite/0.2.17/download -> pin-project-lite-0.2.17.crate
https://crates.io/api/v1/crates/pkcs8/0.10.2/download -> pkcs8-0.10.2.crate
https://crates.io/api/v1/crates/pkg-config/0.3.33/download -> pkg-config-0.3.33.crate
https://crates.io/api/v1/crates/portable-atomic/1.14.0/download -> portable-atomic-1.14.0.crate
https://crates.io/api/v1/crates/portable-atomic-util/0.2.7/download -> portable-atomic-util-0.2.7.crate
https://crates.io/api/v1/crates/potential_utf/0.1.5/download -> potential_utf-0.1.5.crate
https://crates.io/api/v1/crates/powerfmt/0.2.0/download -> powerfmt-0.2.0.crate
https://crates.io/api/v1/crates/primeorder/0.13.6/download -> primeorder-0.13.6.crate
https://crates.io/api/v1/crates/proc-macro2/1.0.107/download -> proc-macro2-1.0.107.crate
https://crates.io/api/v1/crates/prodash/31.0.0/download -> prodash-31.0.0.crate
https://crates.io/api/v1/crates/quote/1.0.47/download -> quote-1.0.47.crate
https://crates.io/api/v1/crates/r-efi/6.0.0/download -> r-efi-6.0.0.crate
https://crates.io/api/v1/crates/rand/0.10.2/download -> rand-0.10.2.crate
https://crates.io/api/v1/crates/rand_core/0.6.4/download -> rand_core-0.6.4.crate
https://crates.io/api/v1/crates/rand_core/0.10.1/download -> rand_core-0.10.1.crate
https://crates.io/api/v1/crates/rand_xoshiro/0.6.0/download -> rand_xoshiro-0.6.0.crate
https://crates.io/api/v1/crates/redox_syscall/0.5.18/download -> redox_syscall-0.5.18.crate
https://crates.io/api/v1/crates/regex/1.13.1/download -> regex-1.13.1.crate
https://crates.io/api/v1/crates/regex-automata/0.4.16/download -> regex-automata-0.4.16.crate
https://crates.io/api/v1/crates/regex-syntax/0.8.11/download -> regex-syntax-0.8.11.crate
https://crates.io/api/v1/crates/rfc6979/0.4.0/download -> rfc6979-0.4.0.crate
https://crates.io/api/v1/crates/rsqlite-vfs/0.1.1/download -> rsqlite-vfs-0.1.1.crate
https://crates.io/api/v1/crates/rusqlite/0.39.0/download -> rusqlite-0.39.0.crate
https://crates.io/api/v1/crates/rustc-hash/2.1.3/download -> rustc-hash-2.1.3.crate
https://crates.io/api/v1/crates/rustc-stable-hash/0.1.2/download -> rustc-stable-hash-0.1.2.crate
https://crates.io/api/v1/crates/rustfix/0.9.7/download -> rustfix-0.9.7.crate
https://crates.io/api/v1/crates/rustix/1.1.4/download -> rustix-1.1.4.crate
https://crates.io/api/v1/crates/rustversion/1.0.23/download -> rustversion-1.0.23.crate
https://crates.io/api/v1/crates/same-file/1.0.6/download -> same-file-1.0.6.crate
https://crates.io/api/v1/crates/schannel/0.1.29/download -> schannel-0.1.29.crate
https://crates.io/api/v1/crates/scopeguard/1.2.0/download -> scopeguard-1.2.0.crate
https://crates.io/api/v1/crates/sec1/0.7.3/download -> sec1-0.7.3.crate
https://crates.io/api/v1/crates/security-framework/3.7.0/download -> security-framework-3.7.0.crate
https://crates.io/api/v1/crates/security-framework-sys/2.17.0/download -> security-framework-sys-2.17.0.crate
https://crates.io/api/v1/crates/semver/1.0.28/download -> semver-1.0.28.crate
https://crates.io/api/v1/crates/serde/1.0.229/download -> serde-1.0.229.crate
https://crates.io/api/v1/crates/serde-untagged/0.1.9/download -> serde-untagged-0.1.9.crate
https://crates.io/api/v1/crates/serde-value/0.7.0/download -> serde-value-0.7.0.crate
https://crates.io/api/v1/crates/serde_core/1.0.229/download -> serde_core-1.0.229.crate
https://crates.io/api/v1/crates/serde_derive/1.0.229/download -> serde_derive-1.0.229.crate
https://crates.io/api/v1/crates/serde_ignored/0.1.14/download -> serde_ignored-0.1.14.crate
https://crates.io/api/v1/crates/serde_json/1.0.150/download -> serde_json-1.0.150.crate
https://crates.io/api/v1/crates/serde_spanned/1.1.1/download -> serde_spanned-1.1.1.crate
https://crates.io/api/v1/crates/sha1/0.10.7/download -> sha1-0.10.7.crate
https://crates.io/api/v1/crates/sha1/0.11.0/download -> sha1-0.11.0.crate
https://crates.io/api/v1/crates/sha1-checked/0.10.0/download -> sha1-checked-0.10.0.crate
https://crates.io/api/v1/crates/sha2/0.10.9/download -> sha2-0.10.9.crate
https://crates.io/api/v1/crates/sha2/0.11.0/download -> sha2-0.11.0.crate
https://crates.io/api/v1/crates/sharded-slab/0.1.7/download -> sharded-slab-0.1.7.crate
https://crates.io/api/v1/crates/shell-escape/0.1.5/download -> shell-escape-0.1.5.crate
https://crates.io/api/v1/crates/shell-words/1.1.1/download -> shell-words-1.1.1.crate
https://crates.io/api/v1/crates/shlex/2.0.1/download -> shlex-2.0.1.crate
https://crates.io/api/v1/crates/signature/2.2.0/download -> signature-2.2.0.crate
https://crates.io/api/v1/crates/simd-adler32/0.3.10/download -> simd-adler32-0.3.10.crate
https://crates.io/api/v1/crates/sized-chunks/0.6.5/download -> sized-chunks-0.6.5.crate
https://crates.io/api/v1/crates/slab/0.4.12/download -> slab-0.4.12.crate
https://crates.io/api/v1/crates/smallvec/1.15.2/download -> smallvec-1.15.2.crate
https://crates.io/api/v1/crates/socket2/0.6.5/download -> socket2-0.6.5.crate
https://crates.io/api/v1/crates/spki/0.7.3/download -> spki-0.7.3.crate
https://crates.io/api/v1/crates/sqlite-wasm-rs/0.5.5/download -> sqlite-wasm-rs-0.5.5.crate
https://crates.io/api/v1/crates/stable_deref_trait/1.2.1/download -> stable_deref_trait-1.2.1.crate
https://crates.io/api/v1/crates/static_assertions/1.1.0/download -> static_assertions-1.1.0.crate
https://crates.io/api/v1/crates/strsim/0.11.1/download -> strsim-0.11.1.crate
https://crates.io/api/v1/crates/subtle/2.6.1/download -> subtle-2.6.1.crate
https://crates.io/api/v1/crates/supports-hyperlinks/3.2.0/download -> supports-hyperlinks-3.2.0.crate
https://crates.io/api/v1/crates/supports-unicode/3.0.0/download -> supports-unicode-3.0.0.crate
https://crates.io/api/v1/crates/syn/2.0.119/download -> syn-2.0.119.crate
https://crates.io/api/v1/crates/syn/3.0.0/download -> syn-3.0.0.crate
https://crates.io/api/v1/crates/synstructure/0.13.2/download -> synstructure-0.13.2.crate
https://crates.io/api/v1/crates/tar/0.4.46/download -> tar-0.4.46.crate
https://crates.io/api/v1/crates/tempfile/3.27.0/download -> tempfile-3.27.0.crate
https://crates.io/api/v1/crates/terminal_size/0.4.4/download -> terminal_size-0.4.4.crate
https://crates.io/api/v1/crates/thiserror/2.0.19/download -> thiserror-2.0.19.crate
https://crates.io/api/v1/crates/thiserror-impl/2.0.19/download -> thiserror-impl-2.0.19.crate
https://crates.io/api/v1/crates/thread_local/1.1.10/download -> thread_local-1.1.10.crate
https://crates.io/api/v1/crates/time/0.3.53/download -> time-0.3.53.crate
https://crates.io/api/v1/crates/time-core/0.1.9/download -> time-core-0.1.9.crate
https://crates.io/api/v1/crates/time-macros/0.2.31/download -> time-macros-0.2.31.crate
https://crates.io/api/v1/crates/tinystr/0.8.3/download -> tinystr-0.8.3.crate
https://crates.io/api/v1/crates/tinyvec/1.12.0/download -> tinyvec-1.12.0.crate
https://crates.io/api/v1/crates/tinyvec_macros/0.1.1/download -> tinyvec_macros-0.1.1.crate
https://crates.io/api/v1/crates/toml/0.9.12+spec-1.1.0/download -> toml-0.9.12+spec-1.1.0.crate
https://crates.io/api/v1/crates/toml/1.1.3+spec-1.1.0/download -> toml-1.1.3+spec-1.1.0.crate
https://crates.io/api/v1/crates/toml_datetime/0.7.5+spec-1.1.0/download -> toml_datetime-0.7.5+spec-1.1.0.crate
https://crates.io/api/v1/crates/toml_datetime/1.1.1+spec-1.1.0/download -> toml_datetime-1.1.1+spec-1.1.0.crate
https://crates.io/api/v1/crates/toml_edit/0.25.13+spec-1.1.0/download -> toml_edit-0.25.13+spec-1.1.0.crate
https://crates.io/api/v1/crates/toml_parser/1.1.2+spec-1.1.0/download -> toml_parser-1.1.2+spec-1.1.0.crate
https://crates.io/api/v1/crates/toml_writer/1.1.2+spec-1.1.0/download -> toml_writer-1.1.2+spec-1.1.0.crate
https://crates.io/api/v1/crates/tracing/0.1.44/download -> tracing-0.1.44.crate
https://crates.io/api/v1/crates/tracing-attributes/0.1.31/download -> tracing-attributes-0.1.31.crate
https://crates.io/api/v1/crates/tracing-chrome/0.7.2/download -> tracing-chrome-0.7.2.crate
https://crates.io/api/v1/crates/tracing-core/0.1.36/download -> tracing-core-0.1.36.crate
https://crates.io/api/v1/crates/tracing-log/0.2.0/download -> tracing-log-0.2.0.crate
https://crates.io/api/v1/crates/tracing-subscriber/0.3.23/download -> tracing-subscriber-0.3.23.crate
https://crates.io/api/v1/crates/typeid/1.0.3/download -> typeid-1.0.3.crate
https://crates.io/api/v1/crates/typenum/1.20.1/download -> typenum-1.20.1.crate
https://crates.io/api/v1/crates/unicase/2.9.0/download -> unicase-2.9.0.crate
https://crates.io/api/v1/crates/unicode-bom/2.0.3/download -> unicode-bom-2.0.3.crate
https://crates.io/api/v1/crates/unicode-ident/1.0.24/download -> unicode-ident-1.0.24.crate
https://crates.io/api/v1/crates/unicode-normalization/0.1.25/download -> unicode-normalization-0.1.25.crate
https://crates.io/api/v1/crates/unicode-width/0.2.2/download -> unicode-width-0.2.2.crate
https://crates.io/api/v1/crates/url/2.5.8/download -> url-2.5.8.crate
https://crates.io/api/v1/crates/utf8_iter/1.0.4/download -> utf8_iter-1.0.4.crate
https://crates.io/api/v1/crates/utf8parse/0.2.2/download -> utf8parse-0.2.2.crate
https://crates.io/api/v1/crates/valuable/0.1.1/download -> valuable-0.1.1.crate
https://crates.io/api/v1/crates/vcpkg/0.2.15/download -> vcpkg-0.2.15.crate
https://crates.io/api/v1/crates/version_check/0.9.5/download -> version_check-0.9.5.crate
https://crates.io/api/v1/crates/walkdir/2.5.0/download -> walkdir-2.5.0.crate
https://crates.io/api/v1/crates/wasi/0.11.1+wasi-snapshot-preview1/download -> wasi-0.11.1+wasi-snapshot-preview1.crate
https://crates.io/api/v1/crates/wasm-bindgen/0.2.126/download -> wasm-bindgen-0.2.126.crate
https://crates.io/api/v1/crates/wasm-bindgen-macro/0.2.126/download -> wasm-bindgen-macro-0.2.126.crate
https://crates.io/api/v1/crates/wasm-bindgen-macro-support/0.2.126/download -> wasm-bindgen-macro-support-0.2.126.crate
https://crates.io/api/v1/crates/wasm-bindgen-shared/0.2.126/download -> wasm-bindgen-shared-0.2.126.crate
https://crates.io/api/v1/crates/winapi/0.3.9/download -> winapi-0.3.9.crate
https://crates.io/api/v1/crates/winapi-i686-pc-windows-gnu/0.4.0/download -> winapi-i686-pc-windows-gnu-0.4.0.crate
https://crates.io/api/v1/crates/winapi-util/0.1.11/download -> winapi-util-0.1.11.crate
https://crates.io/api/v1/crates/winapi-x86_64-pc-windows-gnu/0.4.0/download -> winapi-x86_64-pc-windows-gnu-0.4.0.crate
https://crates.io/api/v1/crates/windows-link/0.2.1/download -> windows-link-0.2.1.crate
https://crates.io/api/v1/crates/windows-sys/0.61.2/download -> windows-sys-0.61.2.crate
https://crates.io/api/v1/crates/winnow/0.7.15/download -> winnow-0.7.15.crate
https://crates.io/api/v1/crates/winnow/1.0.4/download -> winnow-1.0.4.crate
https://crates.io/api/v1/crates/writeable/0.6.3/download -> writeable-0.6.3.crate
https://crates.io/api/v1/crates/yoke/0.8.3/download -> yoke-0.8.3.crate
https://crates.io/api/v1/crates/yoke-derive/0.8.2/download -> yoke-derive-0.8.2.crate
https://crates.io/api/v1/crates/zerofrom/0.1.8/download -> zerofrom-0.1.8.crate
https://crates.io/api/v1/crates/zerofrom-derive/0.1.7/download -> zerofrom-derive-0.1.7.crate
https://crates.io/api/v1/crates/zeroize/1.9.0/download -> zeroize-1.9.0.crate
https://crates.io/api/v1/crates/zerotrie/0.2.4/download -> zerotrie-0.2.4.crate
https://crates.io/api/v1/crates/zerovec/0.11.6/download -> zerovec-0.11.6.crate
https://crates.io/api/v1/crates/zerovec-derive/0.11.3/download -> zerovec-derive-0.11.3.crate
https://crates.io/api/v1/crates/zlib-rs/0.6.6/download -> zlib-rs-0.6.6.crate
https://crates.io/api/v1/crates/zmij/1.0.23/download -> zmij-1.0.23.crate"

LICENSE="Apache-2.0 Boost-1.0 BSD BSD-2 CC0-1.0 ISC LGPL-3+ MIT Apache-2.0 Unlicense ZLIB"
SLOT="0"
KEYWORDS="*"

DEPEND=""
RDEPEND="sys-libs/zlib
	dev-libs/openssl:0=
	dev-vcs/git
	net-misc/curl[ssl]
"
BDEPEND="virtual/rust"

src_unpack() {
	cargo_src_unpack
	rm -rf ${S}
	mv ${WORKDIR}/lu-zero-cargo-c-* ${S} || die
}